// The browser runtime is webpack-dev-middleware's. This writes the files that
// used to be built from `client-src/`, each one re-exporting the middleware's,
// so every `webpack-dev-server/client/...` import keeps resolving to the same
// thing it always did — now one implementation rather than two.
//
// Generated rather than committed because there is no client source here any
// more, and a re-export checked into the repository is still a client file to
// keep in step with the middleware.

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const clientDir = path.join(root, "client");

// Where each published path now comes from. Only the paths that have an
// equivalent are kept: the rest of what `client-src/` built — the log and
// sendMessage helpers, the bundled logger — were this client's own internals,
// and the middleware's client has its own.
const SHIMS = {
  // The runtime itself: what `entry` pointed at, and what the middleware now
  // injects for us. Re-exported so a configuration that lists it by hand, or
  // anything importing it for `setOptionsAndConnect`, still works.
  "index.js": "webpack-dev-middleware/client",
  // The overlay, which other tooling imports directly. The middleware's is
  // the superset of the two, and keeps this project's element id when this
  // server configures it.
  "overlay.js": "webpack-dev-middleware/client/overlay",
  // The progress indicator, named `indicator` there.
  "progress.js": "webpack-dev-middleware/client/indicator",
  // What `client.webSocketTransport` resolves to for each built-in transport,
  // and what a transport of someone else's extends.
  "clients/WebSocketClient.js": "webpack-dev-middleware/client/ws",
  "clients/EventSourceClient.js": "webpack-dev-middleware/client/sse",
  // The connection the runtime holds, as `client` — which is what
  // `@pmmmwh/react-refresh-webpack-plugin` reads its build messages from.
  "socket.js": "webpack-dev-middleware/client/socket",
};

// What a client entry written by hand for this server meant when its query
// left something out: a WebSocket at `/ws`, labelled as this server's, with
// neither the overlay nor progress shown unless the query asks for them. The
// middleware's own defaults are a different endpoint over a different
// transport, so a bare `webpack-dev-server/client/index.js` would never
// connect. The query the entry was given follows these, and wins.
const ENTRY_DEFAULTS = new URLSearchParams({
  transport: "ws",
  pathname: "/ws",
  urlPrefix: "webpack-dev-server",
  logging: JSON.stringify({ name: "webpack-dev-server" }),
  overlay: "false",
  progress: "false",
}).toString();

// Files that were ES modules with a default export a consumer imports by name:
// a class to extend, a function to call. Imported from a CommonJS file, an ES
// module is `module.exports` as a whole for anything that is itself an ES
// module, so these hand back the default export instead, with the rest of what
// the module exports attached to it — `import Client from "…"` gets the class,
// `import { clear } from "…"` still gets the function.
const DEFAULT_EXPORTS = new Set([
  "overlay.js",
  "clients/WebSocketClient.js",
  "clients/EventSourceClient.js",
]);

/**
 * @param {string} from the published path
 * @param {string} to the module it now comes from
 * @returns {string} the file to write
 */
function shim(from, to) {
  // ES5, with no `Object.assign`: these end up in the page's bundle, and a
  // project targeting `["web", "es5"]` gets nothing newer from the client.
  const exported = DEFAULT_EXPORTS.has(from)
    ? `var exported = require("${to}");
var result = exported.default;

for (var key in exported) {
  if (key !== "default") {
    result[key] = exported[key];
  }
}

module.exports = result;`
    : `module.exports = require("${to}");`;

  return `// Generated by scripts/build-client.mjs — do not edit.
//
// \`webpack-dev-server/client/${from}\` is webpack-dev-middleware's client.
// See the "the browser runtime moved" note in the changelog.
${exported}
`;
}

/**
 * The runtime is the one module that is written into `entry` with a query,
 * and the query is on this file rather than on the middleware's. It is handed
 * over before the runtime is required, because the runtime reads its options
 * and connects as it is evaluated.
 * @param {string} from the published path
 * @param {string} to the module it now comes from
 * @returns {string} the file to write
 */
function runtimeShim(from, to) {
  return `// Generated by scripts/build-client.mjs — do not edit.
//
// \`webpack-dev-server/client/${from}\` is webpack-dev-middleware's client.
// See the "the browser runtime moved" note in the changelog.
/* global __resourceQuery */
var defaults = "?${ENTRY_DEFAULTS}";

self.__webpack_dev_middleware_client_query__ =
  typeof __resourceQuery === "string" && __resourceQuery.length > 1
    ? defaults + "&" + __resourceQuery.slice(1)
    : defaults;

module.exports = require("${to}");
`;
}

await fs.rm(clientDir, { recursive: true, force: true });
await fs.mkdir(clientDir, { recursive: true });

// This package is a module, and a module has no `module` or `require`. The
// runtime's stand-in needs both, to hand its query over before the runtime
// evaluates, so this folder is CommonJS. webpack still reads the middleware's
// ES modules through `require`, with their exports intact.
await fs.writeFile(
  path.join(clientDir, "package.json"),
  `${JSON.stringify({ type: "commonjs" }, null, 2)}\n`,
);

for (const [from, to] of Object.entries(SHIMS)) {
  const file = path.join(clientDir, from);

  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(
    file,
    from === "index.js" ? runtimeShim(from, to) : shim(from, to),
  );
}

// eslint-disable-next-line no-console
console.log(
  `client: wrote ${Object.keys(SHIMS).length} re-exports of webpack-dev-middleware's client`,
);
