// The browser runtime is webpack-dev-middleware's. This writes the files that
// used to be built from `client-src/`, each one re-exporting the middleware's,
// so every `webpack-dev-server/client/...` import keeps resolving to the same
// thing it always did — now one implementation rather than two.
//
// Generated rather than committed because there is no client source here any
// more, and a re-export checked into the repository is still a client file to
// keep in step with the middleware.

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const clientDir = path.join(root, "client");

// Where each published path now comes from. Only the paths that have an
// equivalent are kept: the rest of what `client-src/` built — the socket
// wrapper, the log and sendMessage helpers, the bundled logger — were this
// client's own internals, and the middleware's client has its own.
const SHIMS = {
  // The runtime itself: what `entry` pointed at, and what the middleware now
  // injects for us. Re-exported so a configuration that lists it by hand, or
  // anything importing it for `setOptionsAndConnect`, still works.
  "index.js": "webpack-dev-middleware/client",
  // The overlay, which other tooling imports directly. The middleware's is
  // the superset of the two, and keeps this project's element id when this
  // server configures it.
  "overlay.js": "webpack-dev-middleware/client/overlay",
  // The progress indicator, named `indicator` there.
  "progress.js": "webpack-dev-middleware/client/indicator",
  // What `client.webSocketTransport: "ws"` used to resolve to, and what a
  // transport of someone else's extends.
  "clients/WebSocketClient.js": "webpack-dev-middleware/client/ws",
};

/**
 * @param {string} from the published path
 * @param {string} to the module it now comes from
 * @returns {string} the file to write
 */
function shim(from, to) {
  return `// Generated by scripts/build-client.mjs — do not edit.
//
// \`webpack-dev-server/client/${from}\` is webpack-dev-middleware's client.
// See the "the browser runtime moved" note in the changelog.
export * from "${to}";
export { default } from "${to}";
`;
}

await fs.rm(clientDir, { recursive: true, force: true });

for (const [from, to] of Object.entries(SHIMS)) {
  const file = path.join(clientDir, from);

  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, shim(from, to));
}

// eslint-disable-next-line no-console
console.log(
  `client: wrote ${Object.keys(SHIMS).length} re-exports of webpack-dev-middleware's client`,
);
